<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="inchworm">

    <!-- Import Gazebo ROS Control Plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/inchworm</robotNamespace>
        </plugin>
    </gazebo>

    <!-- Links -->
    
    <link name="link1">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://maria_inchworm_description/meshes/inchworm_foot.stl"/>
            </geometry>
        </visual>
    </link>

    
    <link name="base">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 1.5707"/>
            <geometry>
                <mesh filename="package://mavdrive_description/meshes/mavdrive-mk1/MavDrive_Mk1_DemoRobotFrame.stl"/>
            </geometry>
            <material name="mavdrive_mk1_frame_material">
                <color rgba="${46/255} ${49/255} ${49/255} 1"/>
            </material>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="1.5707 0 1.5707"/>
            <mass value="3.692"/> <!-- in kg -->
            <inertia    ixx="0.131821638"
                        ixy="0"
                        iyy="0.26196122"
                        ixz="0"
                        iyz="0"
                        izz="0.131700725" /> <!-- in kg-m^2 -->
        </inertial>
    </link>
    <gazebo reference="base">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="base_2_fl_joint" type="fixed">
        <parent link="base"/>
        <child link="fl_module_base"/>
        <origin xyz="${wheel_base_length/2} ${wheel_base_width/2} -${module_frame_height}" rpy="0.0 0.0 0.0" />
    </joint>

    <joint name="base_2_fr_joint" type="fixed">
        <parent link="base"/>
        <child link="fr_module_base"/>
        <origin xyz="${wheel_base_length/2} -${wheel_base_width/2} -${module_frame_height}" rpy="0.0 0.0 0.0" />
    </joint>

    <joint name="base_2_bl_joint" type="fixed">
        <parent link="base"/>
        <child link="bl_module_base"/>
        <origin xyz="-${wheel_base_length/2} ${wheel_base_width/2} -${module_frame_height}" rpy="0.0 0.0 3.14159" />
    </joint>

    <joint name="base_2_br_joint" type="fixed">
        <parent link="base"/>
        <child link="br_module_base"/>
        <origin xyz="-${wheel_base_length/2} -${wheel_base_width/2} -${module_frame_height}" rpy="0.0 0.0 3.14159" />
    </joint>

</robot>